version: "3"

services:
  better-news: 
    image: better-news
    ports: 
      - 4242:4242
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DISABLE_FORCE_HTTPS=1
      - ENV=development 
      - DEBUG=your-priorities-app 
      - NODE_ENV=development
      - YP_OVERRIDE_LOCALES_CLIENT_FOLDER=better_news
      - APP_NAME=Better News
      - APP_PREFIX=bn
    env_file:
      - amazon-keys.env
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    environment:
      - PORT=6379