version: "2"

services:
  better-news: 
    image: better-news/node-web-app
    ports: 
      - 4242:4242
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DISABLE_FORCE_HTTPS=1
      - ENV=development 
      - DEBUG=your-priorities-app 
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_SECRET_ACCESS_KEY=XXX
      - S3_BUCKET=my-test
      - S3_ENDPOINT=my.s3.website.com
      - YP_OVERRIDE_LOCALES_CLIENT_FOLDER=better_news
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    environment:
      - PORT=6379